#!/usr/bin/env python3
"""
ASIC AUTHENTICATION PORTAL (V1)
==============================
Unified interface to Verify or Sign images using Antminer S9 hardware.
1. Check if image is already ASIC-signed.
2. If yes -> Alert!
3. If no -> Authenticate via Silicon Signature.
"""

import os
import sys
import time
from verify_silicon_art import verify_art
from silicon_signature_engine import get_silicon_signature

def main(image_path):
    print("=" * 60)
    print("ASIC AUTHENTICATION PORTAL")
    print("=" * 60)
    
    if not os.path.exists(image_path):
        print(f"[ERROR] File not found: {image_path}")
        return

    # STEP 1: Identification
    print(f"[STEP 1] Inspecting Image Structure: {os.path.basename(image_path)}...")
    is_asic = False
    try:
        # verify_art returns True if valid ASIC signature found
        is_asic = verify_art(image_path)
    except Exception as e:
        print(f"[DEBUG] Verification failed: {e}")

    if is_asic:
        print("\n" + "!" * 60)
        print("ALARM: This image was generated by ASIC.")
        print("Structure: Verified BM1387 Deterministic Fog.")
        print("!" * 60 + "\n")
        return
    else:
        print("[INFO] No valid ASIC signature detected. Proceeding to Authentication...")

    # STEP 2: Authentication
    print(f"\n[STEP 2] Launching BM1387 Signature Loop...")
    result_path = get_silicon_signature(image_path)
    
    if result_path:
        print("\n" + "=" * 60)
        print("SUCCESS: Image Authenticated by Silicon.")
        print(f"Result: {os.path.basename(result_path)}")
        print("=" * 60)
    else:
        print("\n[ERROR] Authentication failed. Ensure S9 Bridge is running.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python asic_auth_portal.py <path_to_image>")
    else:
        main(sys.argv[1])
